name: /Users/sternsemasuka/Desktop/ML/Project/Income-classification/.income_class
channels:
  - conda-forge
dependencies:
  - abseil-cpp=20210324.2=hbdafb3b_0
  - altair=4.2.0=pyhd8ed1ab_1
  - appnope=0.1.2=py39h2804cbe_2
  - argh=0.26.2=pyh9f0ad1d_1002
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39h5161555_1
  - arrow-cpp=6.0.1=py39h71c7f51_5_cpu
  - astor=0.8.1=pyh9f0ad1d_0
  - asttokens=2.0.5=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - aws-c-auth=0.6.8=h77ca94e_1
  - aws-c-cal=0.5.12=hc1327b6_7
  - aws-c-common=0.6.17=h3422bc3_0
  - aws-c-compression=0.2.14=haaffe3e_7
  - aws-c-event-stream=0.2.7=hd0ff547_32
  - aws-c-http=0.6.10=h53b0524_3
  - aws-c-io=0.10.14=h3e85fa9_1
  - aws-c-mqtt=0.7.10=hd8b1cef_0
  - aws-c-s3=0.1.29=h6db2689_0
  - aws-c-sdkutils=0.1.1=haaffe3e_4
  - aws-checksums=0.1.12=haaffe3e_6
  - aws-crt-cpp=0.17.10=h5d9c0f4_5
  - aws-sdk-cpp=1.9.160=he5b1d48_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - base58=2.1.1=pyhd8ed1ab_0
  - black=21.12b0=pyhd8ed1ab_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - blinker=1.4=py_1
  - boto3=1.20.34=pyhd8ed1ab_0
  - botocore=1.23.46=pyhd8ed1ab_0
  - brotli=1.0.9=h3422bc3_6
  - brotli-bin=1.0.9=h3422bc3_6
  - brotlipy=0.7.0=py39h5161555_1003
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2021.10.8=h4653dfc_0
  - cachetools=5.0.0=pyhd8ed1ab_0
  - certifi=2021.10.8=py39h2804cbe_1
  - cffi=1.15.0=py39h52b1de0_0
  - charset-normalizer=2.0.10=pyhd8ed1ab_0
  - click=7.1.2=pyh9f0ad1d_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=36.0.1=py39hfb8cd70_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.5.1=py39hfb83b0d_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - executing=0.8.2=pyhd8ed1ab_0
  - flit-core=3.6.0=pyhd8ed1ab_0
  - fonttools=4.29.0=py39h5161555_0
  - freetype=2.10.4=h17b34a0_1
  - gflags=2.2.2=hc88da5d_1004
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.26=pyhd8ed1ab_0
  - glog=0.5.0=h5c6a83d_0
  - grpc-cpp=1.42.0=hedfbb7c_1
  - htmlmin=0.1.12=py_1
  - idna=3.3=pyhd8ed1ab_0
  - imagehash=4.2.1=pyhd8ed1ab_0
  - imbalanced-learn=0.9.0=pyhd8ed1ab_0
  - importlib-metadata=4.10.1=py39h2804cbe_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - ipykernel=6.7.0=py39h32adebf_0
  - ipython=8.0.1=py39h2804cbe_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - jbig=2.1=h3422bc3_2003
  - jedi=0.18.1=py39h2804cbe_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9e=h3422bc3_0
  - jsonschema=4.4.0=pyhd8ed1ab_0
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py39h2804cbe_1
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - kiwisolver=1.3.2=py39h4d2d688_1
  - krb5=1.19.2=hd92b7a7_3
  - lcms2=2.12=had6a04f_0
  - lerc=3.0=hbdafb3b_0
  - libblas=3.9.0=13_osxarm64_openblas
  - libbrotlicommon=1.0.9=h3422bc3_6
  - libbrotlidec=1.0.9=h3422bc3_6
  - libbrotlienc=1.0.9=h3422bc3_6
  - libcblas=3.9.0=13_osxarm64_openblas
  - libcurl=7.81.0=h8fe1914_0
  - libcxx=12.0.1=h168391b_1
  - libdeflate=1.8=h3422bc3_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libevent=2.1.10=hbae9a57_4
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0.dev0=11_0_1_hf114ba7_23
  - libgfortran5=11.0.1.dev0=hf114ba7_23
  - liblapack=3.9.0=13_osxarm64_openblas
  - libllvm10=10.0.1=h4468dd5_2
  - libnghttp2=1.46.0=he4cd7f6_0
  - libopenblas=0.3.18=openmp_h5dd58f0_0
  - libpng=1.6.37=hf7e6567_2
  - libprotobuf=3.19.3=hccf11d3_0
  - libsodium=1.0.18=h27ca646_1
  - libssh2=1.10.0=hb80f160_2
  - libthrift=0.15.0=h28a9c34_1
  - libtiff=4.3.0=h74060c4_2
  - libutf8proc=2.7.0=h3422bc3_0
  - libwebp-base=1.2.2=h3422bc3_1
  - libzlib=1.2.11=hee7b306_1013
  - llvm-openmp=12.0.1=hf3c4609_1
  - llvmlite=0.36.0=py39h2f15362_0
  - lz4-c=1.9.3=hbdafb3b_1
  - markupsafe=2.0.1=py39h5161555_1
  - matplotlib=3.5.1=py39hdf13c20_0
  - matplotlib-base=3.5.1=py39h5aa4fe7_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - missingno=0.4.2=py_1
  - mistune=0.8.4=py39h5161555_1005
  - multimethod=1.4=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=0.4.3=py39h2804cbe_4
  - nbclient=0.5.10=pyhd8ed1ab_1
  - nbconvert=6.4.1=py39h2804cbe_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.3=hc470f4d_0
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - networkx=2.6.3=pyhd8ed1ab_1
  - notebook=6.4.8=pyha770c72_0
  - numba=0.53.1=py39hbdc0675_1
  - numpy=1.22.0=py39h61a45d2_1
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h062765e_1
  - openssl=1.1.1l=h3422bc3_0
  - orc=1.7.1=hcb6706d_1
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.5=py39h7f752ed_0
  - pandas-profiling=3.1.0=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parquet-cpp=1.5.1=2
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - phik=0.11.2=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=8.4.0=py39ha74c66e_0
  - pip=22.0.2=pyhd8ed1ab_0
  - platformdirs=2.3.0=pyhd8ed1ab_0
  - prometheus_client=0.13.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.26=pyha770c72_0
  - protobuf=3.19.3=py39hfb83b0d_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=6.0.1=py39hd3b58d7_5_cpu
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.9.0=py39h5161555_0
  - pydeck=0.7.1=pyh6c4a22f_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pympler=0.9=pyh9f0ad1d_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py39h5161555_0
  - pysocks=1.7.1=py39h2804cbe_4
  - python=3.9.10=hd16f9c5_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2021.5=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2021.3=pyhd8ed1ab_0
  - pytz-deprecation-shim=0.1.0.post0=py39h2804cbe_1
  - pywavelets=1.2.0=py39h20ef057_1
  - pyyaml=6.0=py39h5161555_3
  - pyzmq=22.3.0=py39h02c6a76_1
  - re2=2021.11.01=hbdafb3b_0
  - readline=8.1=hedafd6a_0
  - requests=2.27.1=pyhd8ed1ab_0
  - s3transfer=0.5.0=pyhd8ed1ab_0
  - scikit-learn=1.0.2=py39hef7049f_0
  - scipy=1.7.3=py39h5060c3b_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=59.8.0=py39h2804cbe_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.8=hc88da5d_3
  - sqlite=3.37.0=h72a2b83_0
  - stack_data=0.1.4=pyhd8ed1ab_0
  - statsmodels=0.13.1=py39h20ef057_0
  - streamlit=1.3.1=pyhd8ed1ab_0
  - tangled-up-in-unicode=0.1.0=pyhd8ed1ab_0
  - terminado=0.13.1=py39h2804cbe_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=3.0.0=pyh8a188c0_0
  - tk=8.6.11=he1e0b03_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=1.2.2=pyhd8ed1ab_0
  - toolz=0.11.2=pyhd8ed1ab_0
  - tornado=6.1=py39h5161555_2
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typed-ast=1.5.2=py39h5161555_0
  - typing-extensions=4.0.1=hd8ed1ab_0
  - typing_extensions=4.0.1=pyha770c72_0
  - tzdata=2021e=he74cb21_0
  - tzlocal=4.1=py39h2804cbe_1
  - unicodedata2=14.0.0=py39h5161555_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - validators=0.18.2=pyhd3deb0d_0
  - visions=0.7.4=pyhd8ed1ab_0
  - watchdog=2.1.6=py39h5161555_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.5.2=py39h2804cbe_1
  - xz=5.2.5=h642e427_1
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.7.0=pyhd8ed1ab_0
  - zlib=1.2.11=hee7b306_1013
  - zstd=1.5.2=h861e0a7_0
  - pip:
    - streamlit-lottie==0.0.3
prefix: /Users/sternsemasuka/Desktop/ML/Project/Income-classification/.income_class
